# Colors ---------------------------------------------------------------------

[colors]
background = "#1a1b26F0"
text_primary = "#c0caf5FF"
text_muted = "#565f89FF"
accent_primary = "#7aa2f7FF"
accent_secondary = "#eecf66FF"
warning = "#eecf66FF"
error = "#f7768eFF"

# Appearance -----------------------------------------------------------------

[appearance]
prefer_no_csd = true
border_width = 3       # 0-100
outer_border_width = 0 # 0-100
corner_radius = 14     # 0-100
# animation_ms = 250                        # 1-10000
drag_opacity = 0.75
border_focused = "#7aa2f7ff"
border_unfocused = "#414868ff"
scratchpad_border_focused = "#eecf66ff"
scratchpad_border_unfocused = "#565f89ff"
outer_border_color = "#16161eff"
insert_hint_color = "#7dcfff80"
backdrop_color = "#1a1b26ff"

[appearance.blur]
enabled = false
optimized = true
passes = 3       # 0-8
radius = 3       # 0-100
noise = 0.02     # 0.0-1.0
brightness = 0.9 # 0.0-2.0
contrast = 0.9   # 0.0-2.0
saturation = 1.1 # 0.0-2.0

[appearance.shadow]
enabled = true
softness = 15       # 0-200, 0 = hard edge
offset_x = 0        # -200 to 200
offset_y = 3
color = "#16161e7f"
