[include]
files = [
  "general.toml",
  "appearance.toml",
  "animation.toml",
  "overview.toml",
  "layout.toml",
  "outputs.toml",
  "input.toml",
  "keybinds.toml",
  "rules.toml",
  "touchpad.toml"
]
