# Keybinds -----------------------------------------------------------

[keybinds]
# Media & Brightness Controls
"XF86AudioRaiseVolume" = { action = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.02+", allow_when_locked = true }
"XF86AudioLowerVolume" = { action = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.02-", allow_when_locked = true }
"XF86AudioMute" = { action = "spawn:wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle", allow_when_locked = true }
"XF86AudioMicMute" = { action = "spawn:wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle", allow_when_locked = true }
"XF86AudioPlay" = { action = "spawn:playerctl play", allow_when_locked = true }
"XF86AudioPause" = { action = "spawn:playerctl pause", allow_when_locked = true }
"XF86AudioNext" = { action = "spawn:playerctl next", allow_when_locked = true }
"XF86AudioPrev" = { action = "spawn:playerctl previous", allow_when_locked = true }
"Mod+Shift+M" = { action = "spawn:playerctl play-pause", allow_when_locked = true }

"XF86MonBrightnessUp" = { action = "spawn:brightnessctl set +2%", allow_when_locked = true }
"XF86MonBrightnessDown" = { action = "spawn:brightnessctl set 2%-", allow_when_locked = true }
"Mod+F6" = { action = "spawn:brightnessctl set +2%", allow_when_locked = true }
"Mod+F5" = { action = "spawn:brightnessctl set 2%-", allow_when_locked = true }

# Applications
"Mod+Return" = "spawn:kitty"
"Mod+Shift+Space" = "spawn:fuzzel"
"Mod+B" = "spawn:zen-browser"
"Mod+Shift+B" = "spawn:helium-browser"
"Mod+M" = "spawn:kitty -e sh -c 'systemctl --user is-active --quiet mpd || { systemctl --user start mpd && sleep 0.5; }; exec rmpc'"
"Mod+D" = "spawn:vesktop --ozone-platform-hint=auto --enable-blink-features=MiddleClickAutoscroll"
"Mod+Shift+S" = "spawn:fsearch"
"Mod+Shift+E" = "spawn:nautilus"
"Mod+E" = "spawn:kitty -e yazi"
"XF86Calculator" = "spawn:qalculate-qt"
"Mod+Shift+Escape" = "spawn:kitty -e btop"
"Mod+N" = "spawn:kitty -e nvim"
"Mod+Shift+N" = "spawn:kitty -e emacs"
"Mod+S" = "spawn:localsend"

# Custom Scripts
# "Mod+F1" = { action = "spawn:tlpctl-cycle", allow_when_locked = true }
"Mod+F10" = { action = "spawn:/home/antariksh/.local/bin/toggle-touchpad", allow_when_locked = true }

# Screenshots & Utilites
"Ctrl+Shift+1" = "spawn:noctalia msg screenshot-region"
"Ctrl+Shift+2" = "spawn:noctalia msg screenshot-fullscreen"
"Ctrl+Shift+3" = "spawn:noctalia msg screenshot-fullscreen all"
"Ctrl+Shift+4" = { action = "spawn:noctalia msg plugin noctalia/screen_recorder:service all toggle", allow_when_locked = true }
"Ctrl+Shift+5" = "spawn:hyprpicker -a"
"Ctrl+Shift+6" = "spawn:wayscriber --active"
"Ctrl+Shift+7" = "spawn:wooz --invert-scroll"

# Noctalia
"Mod+Space" = "spawn:noctalia msg panel-toggle launcher"
"Mod+Grave" = "spawn:noctalia msg bar-toggle"
"Mod+Shift+Comma" = "spawn:noctalia msg settings-toggle"
"Mod+Z" = "spawn:noctalia msg panel-toggle control-center"
"Mod+V" = "spawn:noctalia msg panel-toggle clipboard"
"Mod+semicolon" = "spawn:noctalia msg panel-toggle launcher '/emo '"
"Mod+W" = "spawn:noctalia msg panel-toggle wallpaper"

# --- System & Session ---                                                                                                     
"Ctrl+Alt+Delete" = "session-quit"
"Mod+Shift+P" = "dpms-off"
"Ctrl+Mod+Space" = "keyboard-layout-next"
"Mod+F1" = "spawn:noctalia msg power-cycle"
"Mod+X" = "spawn:noctalia msg panel-toggle session"
"Alt+Mod+L" = "spawn:noctalia msg session lock"
"Alt+Mod+S" = { action = "spawn:noctalia msg session lock-and-suspend", allow_when_locked = true }
"XF86PowerOff" = { action = "spawn:noctalia msg session lock-and-suspend", allow_when_locked = true }

# --- Window Management & Movement ---
# Base Actions
"Mod+Q" = "window-close"
"Mod+T" = "window-toggle-floating"
"Mod+Shift+T" = "window-focus-switch-floating"
"Mod+F" = "window-toggle-maximize"
"Mod+Shift+F" = "window-toggle-fullscreen"
"Mod+C" = "column-center"
"Mod+Shift+C" = "window-center"
"Mod+O" = "overview-toggle"
"Mod+Minus" = "window-modify-width:-0.05"
"Mod+Equal" = "window-modify-width:+0.05"
"Mod+Shift+Minus" = "window-modify-height:-0.05"
"Mod+Shift+Equal" = "window-modify-height:+0.05"
"Mod+P" = "window-toggle-pinned"
"Mod+R" = "window-cycle-width"
"Mod+Shift+R" = "window-cycle-height"
"Alt+Tab" = "spawn:noctalia msg window-switcher"

# Focus
"Mod+Left" = "window-focus-left"
"Mod+Right" = "window-focus-right"
"Mod+Up" = "window-focus-up"
"Mod+Down" = "window-focus-down"
"Mod+H" = "window-focus-left"
"Mod+L" = "window-focus-right"
"Mod+K" = "window-focus-up"
"Mod+J" = "window-focus-down"

# Move Windows
"Mod+Ctrl+Left" = "column-move-left"
"Mod+Ctrl+Right" = "column-move-right"
"Mod+Ctrl+Up" = "window-move-up"
"Mod+Ctrl+Down" = "window-move-down"
"Mod+Ctrl+H" = "column-move-left"
"Mod+Ctrl+L" = "column-move-right"
"Mod+Ctrl+K" = "window-move-up"
"Mod+Ctrl+J" = "window-move-down"

# Consume / Expel
"Mod+Comma" = "window-consume-or-expel-left"
"Mod+Period" = "window-consume-or-expel-right"

# Column Management & Movement
# Home / End
"Mod+Home" = "column-focus-first"
"Mod+End" = "column-focus-last"
"Mod+Ctrl+Home" = "column-move-to-first"
"Mod+Ctrl+End" = "column-move-to-last"

# --- Multi-Monitor Movement ---
# Focus
"Mod+Shift+Left" = "output-focus-left"
"Mod+Shift+Right" = "output-focus-right"
"Mod+Shift+Up" = "output-focus-up"
"Mod+Shift+Down" = "output-focus-down"
"Mod+Shift+H" = "output-focus-left"
"Mod+Shift+L" = "output-focus-right"
"Mod+Shift+K" = "output-focus-up"
"Mod+Shift+J" = "output-focus-down"

# Column 
"Mod+Shift+Ctrl+Left" = "column-move-to-output-left"
"Mod+Shift+Ctrl+Right" = "column-move-to-output-right"
"Mod+Shift+Ctrl+Up" = "column-move-to-output-up"
"Mod+Shift+Ctrl+Down" = "column-move-to-output-down"
"Mod+Shift+Ctrl+H" = "column-move-to-output-left"
"Mod+Shift+Ctrl+L" = "column-move-to-output-right"
"Mod+Shift+Ctrl+K" = "column-move-to-output-up"
"Mod+Shift+Ctrl+J" = "column-move-to-output-down"

# --- Workspace --- 
# Switching
"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"

"Mod+Ctrl+1" = "window-move-to-workspace:1"
"Mod+Ctrl+2" = "window-move-to-workspace:2"
"Mod+Ctrl+3" = "window-move-to-workspace:3"
"Mod+Ctrl+4" = "window-move-to-workspace:4"
"Mod+Ctrl+5" = "window-move-to-workspace:5"
"Mod+Ctrl+6" = "window-move-to-workspace:6"
"Mod+Ctrl+7" = "window-move-to-workspace:7"
"Mod+Ctrl+8" = "window-move-to-workspace:8"
"Mod+Ctrl+9" = "window-move-to-workspace:9"

# Relative
"Mod+I" = "workspace-next"
"Mod+U" = "workspace-previous"
"Mod+Ctrl+I" = "window-move-to-workspace-next"
"Mod+Ctrl+U" = "window-move-to-workspace-previous"
"Mod+Shift+U" = "workspace-move-up"
"Mod+Shift+I" = "workspace-move-down"
"Mod+WheelDown" = "workspace-next"
"Mod+WheelUp" = "workspace-previous"
"Mod+Ctrl+WheelDown" = "window-move-to-workspace-next"
"Mod+Ctrl+WheelUp" = "window-move-to-workspace-previous"

# --- Scratchpads ---
"Mod+Backspace" = "scratchpad-toggle"
"Mod+Shift+Backspace" = "window-toggle-scratchpad"
"Mod+Tab" = "scratchpad-focus-next"
