music_directory	"~/Music/"

playlist_directory "~/Music/Playlists/"

db_file	"~/.config/mpd/database"

state_file "~/.local/state/mpd/state"

# sticker_file "~/.config/mpd/sticker.sql"

restore_paused "yes"

save_absolute_paths_in_playlists "yes"

auto_update	"yes"

follow_outside_symlinks	"yes"

follow_inside_symlinks "yes"

audio_output {
  type "pipewire"
  name "PipeWire Audio"
}

replaygain "track"
replaygain_limit "yes"
replaygain_preamp "3"
