general {
  lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
}

listener {
  timeout = 180 # 3 min
  on-timeout = brightnessctl -s set 6%
  on-resume = brightnessctl -r
}

listener {
  timeout = 300 # 5 min 
  on-timeout = qs -c noctalia-shell ipc call lockScreen lock
}

listener {
  timeout = 360 # 6 min
  on-timeout = niri msg action power-off-monitors
  on-resume = niri msg action power-on-monitors
}

listener {
  timeout = 1200 # 20 min
  on-timeout = systemctl suspend
}
