# Keymaps for plugins

[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"

[[mgr.prepend_keymap]]
on = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders"

[[mgr.prepend_keymap]]
on = "U"
run = "plugin restore -- --interactive --interactive-overwrite"
desc = "Restore deleted files/folders (Interactive overwrite)"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"
