stop-screensaver=yes 
save-position-on-quit=yes
keep-open=yes

vo=gpu-next,gpu
gpu-api=vulkan
gpu-context=waylandvk
hwdec=vaapi
profile=high-quality
autofit-larger=100%x100%

volume-max=300

osc=no
osd-bar=no	
osd-duration=2000		

sub-visibility=yes
sub-auto=fuzzy

screenshot-format=png
screenshot-png-compression=7
screenshot-directory="/home/antariksh/Pictures/Screenshots"
screenshot-template="%ts"
